# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Southern Catholic Mom"
description: > # this means to ignore newlines until "email:"
  Adventures, giggles, tears and confessions of a first time mommy

email: blg2790@gmail.com
#blog logo
logo: "/assets/images/beccapic.jpg"
float_logo: false # true, false (default)

# blog cover
cover: "/assets/images/familypic.jpg"

name: 'Becca McCaskey'
author: 'Becca McCaskey'
author_image: "/assets/images/beccapic.jpg"

paginate:	5

url: "https://beccamccaskey.github.io/southerncatholicmom" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@becca_goldman'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/becca_goldman
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon: instagram
    url: https://instagram.com/beccalane22
    desc: Follow me on Instagram
    
  - icon:	facebook
    url:	https://www.facebook.com/becca.goldman.9
    desc: Connect with me facebook
    share_url: https://www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

    #  - icon:	github
    #url:	https://github.com/dirkfabisch
    #desc:	Fork me on github
    #share_url:
    #share_title:
    #    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
